/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artists */
        get: operations["artists_api_v1_artists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Artist */
        post: operations["create_artist_api_v1_admin_artists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/artists/{artist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Artist */
        put: operations["update_artist_api_v1_admin_artists__artist_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_v1_posters_get"];
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_posters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posters/{poster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Poster */
        get: operations["get_poster_api_v1_posters__poster_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/posters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queue */
        get: operations["queue_api_v1_admin_posters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/posters/{poster_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poster Image */
        get: operations["poster_image_api_v1_admin_posters__poster_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/posters/{poster_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_v1_admin_posters__poster_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/background": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Background */
        get: operations["background_api_v1_events__event_id__background_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidates */
        get: operations["list_candidates_api_v1_admin_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/candidates/{candidate_id}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Candidate Source */
        get: operations["compare_candidate_source_api_v1_admin_candidates__candidate_id__comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/candidates/{candidate_id}/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrich Candidate */
        post: operations["enrich_candidate_api_v1_admin_candidates__candidate_id__enrich_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/candidates/{candidate_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Candidate */
        post: operations["approve_candidate_api_v1_admin_candidates__candidate_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/candidates/{candidate_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Candidate */
        post: operations["reject_candidate_api_v1_admin_candidates__candidate_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_admin_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_v1_admin_events__event_id__get"];
        /** Update Event */
        put: operations["update_event_api_v1_admin_events__event_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/events/{event_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Event Revisions */
        get: operations["list_event_revisions_api_v1_admin_events__event_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Corrections */
        get: operations["list_corrections_api_v1_admin_corrections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/corrections/{correction_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Correction */
        post: operations["review_correction_api_v1_admin_corrections__correction_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Map Events */
        get: operations["map_events_api_v1_events_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/nearby-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nearby Updates */
        get: operations["nearby_updates_api_v1_events_nearby_updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Correction */
        post: operations["create_correction_api_v1_corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_v1_meta_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminCandidate */
        AdminCandidate: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            /** Organizer */
            organizer: string | null;
            /** Price */
            price: string | null;
            /** Venue Name */
            venue_name: string | null;
            /** Address */
            address: string | null;
            /** City */
            city: string | null;
            /** District */
            district: string | null;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            enrichment?: components["schemas"]["EnrichmentInfo"];
            /** Starts At */
            starts_at: string | null;
            /** Ends At */
            ends_at: string | null;
            /** Official Url */
            official_url: string;
            /** Facts */
            facts: {
                [key: string]: unknown;
            };
            review_status: components["schemas"]["CandidateReviewStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Event Id */
            event_id: string | null;
            /** Reviewed By */
            reviewed_by: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Review Note */
            review_note: string | null;
        };
        /** AdminCorrection */
        AdminCorrection: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Event Id */
            event_id: string | null;
            /** Kind */
            kind: string;
            /** Message */
            message: string;
            /** Evidence Url */
            evidence_url: string | null;
            /** Contact Email */
            contact_email: string | null;
            status: components["schemas"]["CorrectionStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reviewed By */
            reviewed_by: string | null;
            /** Resolution Note */
            resolution_note: string | null;
        };
        /** AdminEventDetail */
        AdminEventDetail: {
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            /** Summary */
            summary: string;
            /** Description */
            description: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Venue Name */
            venue_name: string;
            /** Address */
            address: string;
            /** City */
            city: string;
            /** District */
            district: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Organizer */
            organizer: string;
            /** Price */
            price?: string | null;
            status: components["schemas"]["EventStatus"];
            /**
             * Evidence Url
             * Format: uri
             */
            evidence_url: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Is Published */
            is_published: boolean;
        };
        /** AdminEventRevision */
        AdminEventRevision: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** Correction Id */
            correction_id: string | null;
            /** Note */
            note: string;
            /** Before */
            before: {
                [key: string]: unknown;
            };
            /** After */
            after: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AdminEventUpdate */
        AdminEventUpdate: {
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            /** Summary */
            summary: string;
            /** Description */
            description: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Venue Name */
            venue_name: string;
            /** Address */
            address: string;
            /** City */
            city: string;
            /** District */
            district: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Organizer */
            organizer: string;
            /** Price */
            price?: string | null;
            status: components["schemas"]["EventStatus"];
            /**
             * Evidence Url
             * Format: uri
             */
            evidence_url: string;
            /**
             * Expected Updated At
             * Format: date-time
             */
            expected_updated_at: string;
            /** Review Note */
            review_note: string;
            /** Is Published */
            is_published: boolean;
        };
        /** ArtistInput */
        ArtistInput: {
            /** Name */
            name: string;
            /** Birth Date */
            birth_date?: string | null;
            /**
             * Gender
             * @default
             */
            gender: string;
            /**
             * Hometown
             * @default
             */
            hometown: string;
            /** Aliases */
            aliases?: string[];
            /**
             * Fan Name
             * @default
             */
            fan_name: string;
            /**
             * Support Color
             * @default
             */
            support_color: string;
            /**
             * Agency
             * @default
             */
            agency: string;
            /**
             * Honors
             * @default
             */
            honors: string;
            /** Works */
            works?: components["schemas"]["Work"][];
            /** References */
            references?: components["schemas"]["Reference"][];
        };
        /** CandidateApproval */
        CandidateApproval: {
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            /** Summary */
            summary: string;
            /** Description */
            description: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Venue Name */
            venue_name: string;
            /** Address */
            address: string;
            /** City */
            city: string;
            /** District */
            district: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Organizer */
            organizer: string;
            /** Price */
            price?: string | null;
            status: components["schemas"]["EventStatus"];
            /**
             * Evidence Url
             * Format: uri
             */
            evidence_url: string;
            /**
             * Expected Updated At
             * Format: date-time
             */
            expected_updated_at: string;
            /** Review Note */
            review_note: string;
        };
        /** CandidateComparison */
        CandidateComparison: {
            /** Event Id */
            event_id: string | null;
            /** Changes */
            changes: components["schemas"]["FieldChange"][];
        };
        /** CandidateEnrich */
        CandidateEnrich: {
            /**
             * Expected Updated At
             * Format: date-time
             */
            expected_updated_at: string;
        };
        /** CandidateRejection */
        CandidateRejection: {
            /**
             * Expected Updated At
             * Format: date-time
             */
            expected_updated_at: string;
            /** Review Note */
            review_note: string;
        };
        /**
         * CandidateReviewStatus
         * @enum {string}
         */
        CandidateReviewStatus: "pending" | "approved" | "rejected";
        /** CategoriesResponse */
        CategoriesResponse: {
            /** Data */
            data: components["schemas"]["CategoryOption"][];
        };
        /** CategoryOption */
        CategoryOption: {
            value: components["schemas"]["EventCategory"];
            /** Label */
            label: string;
        };
        /** CorrectionCreate */
        CorrectionCreate: {
            /** Event Id */
            event_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "time" | "location" | "status" | "source" | "copyright" | "other";
            /** Message */
            message: string;
            /** Evidence Url */
            evidence_url?: string | null;
            /** Contact Email */
            contact_email?: string | null;
        };
        /** CorrectionReceipt */
        CorrectionReceipt: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["CorrectionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CorrectionResponse */
        CorrectionResponse: {
            data: components["schemas"]["CorrectionReceipt"];
        };
        /** CorrectionReview */
        CorrectionReview: {
            /**
             * Expected Updated At
             * Format: date-time
             */
            expected_updated_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "reviewing" | "accepted" | "rejected";
            /** Resolution Note */
            resolution_note: string;
            event_update?: components["schemas"]["AdminEventUpdate"] | null;
        };
        /**
         * CorrectionStatus
         * @enum {string}
         */
        CorrectionStatus: "pending" | "reviewing" | "accepted" | "rejected";
        /** Credentials */
        Credentials: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** EnrichmentInfo */
        EnrichmentInfo: {
            /**
             * Detail Status
             * @default not_requested
             * @enum {string}
             */
            detail_status: "not_requested" | "ok" | "unavailable";
            /** Detail Url */
            detail_url?: string | null;
            /** Venue Url */
            venue_url?: string | null;
            /** Time Text */
            time_text?: string | null;
            /** Location Method */
            location_method?: ("showstart" | "amap") | null;
            source_coordinates?: components["schemas"]["SourceCoordinates"] | null;
            /** Warnings */
            warnings?: string[];
            /** Place Matches */
            place_matches?: components["schemas"]["PlaceMatch"][];
        };
        /**
         * EventCategory
         * @enum {string}
         */
        EventCategory: "performance" | "sports" | "exhibition" | "festival" | "market" | "public_culture" | "pop_up" | "seasonal";
        /** EventDetail */
        EventDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            /** Summary */
            summary: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            location: components["schemas"]["Location"];
            /** Organizer */
            organizer: string;
            /** Price */
            price?: string | null;
            status: components["schemas"]["EventStatus"];
            /**
             * Last Verified At
             * Format: date-time
             */
            last_verified_at: string;
            /** Confidence */
            confidence: number;
            /** Attributes */
            attributes: string[];
            /** Is Ad */
            is_ad: boolean;
            /** Is Demo */
            is_demo: boolean;
            /** Is New */
            is_new: boolean;
            /** Is Ending Soon */
            is_ending_soon: boolean;
            /** Description */
            description: string;
            /** Official Url */
            official_url: string;
            /** Sources */
            sources: components["schemas"]["SourceEvidence"][];
            /** Status History */
            status_history: components["schemas"]["StatusHistoryPublic"][];
        };
        /** EventDetailResponse */
        EventDetailResponse: {
            data: components["schemas"]["EventDetail"];
        };
        /** EventFields */
        EventFields: {
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            /** Summary */
            summary: string;
            /** Description */
            description: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Venue Name */
            venue_name: string;
            /** Address */
            address: string;
            /** City */
            city: string;
            /** District */
            district: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Organizer */
            organizer: string;
            /** Price */
            price?: string | null;
            status: components["schemas"]["EventStatus"];
            /**
             * Evidence Url
             * Format: uri
             */
            evidence_url: string;
        };
        /** EventPage */
        EventPage: {
            /** Data */
            data: components["schemas"]["EventSummary"][];
            meta: components["schemas"]["PageMeta"];
        };
        /**
         * EventStatus
         * @enum {string}
         */
        EventStatus: "announced" | "on_sale" | "sold_out" | "postponed" | "cancelled" | "ended";
        /** EventSummary */
        EventSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            /** Summary */
            summary: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            location: components["schemas"]["Location"];
            /** Organizer */
            organizer: string;
            /** Price */
            price?: string | null;
            status: components["schemas"]["EventStatus"];
            /**
             * Last Verified At
             * Format: date-time
             */
            last_verified_at: string;
            /** Confidence */
            confidence: number;
            /** Attributes */
            attributes: string[];
            /** Is Ad */
            is_ad: boolean;
            /** Is Demo */
            is_demo: boolean;
            /** Is New */
            is_new: boolean;
            /** Is Ending Soon */
            is_ending_soon: boolean;
        };
        /** FieldChange */
        FieldChange: {
            /** Field */
            field: string;
            /** Before */
            before: string | null;
            /** After */
            after: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Location */
        Location: {
            /** Venue Name */
            venue_name: string;
            /** Address */
            address: string;
            /** City */
            city: string;
            /** District */
            district: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["UserPublic"];
        };
        /** MapEvent */
        MapEvent: {
            /** Published At */
            published_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            status: components["schemas"]["EventStatus"];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** MapEventsResponse */
        MapEventsResponse: {
            /** Data */
            data: components["schemas"]["MapEvent"][];
            meta: components["schemas"]["MapPageMeta"];
        };
        /** MapPageMeta */
        MapPageMeta: {
            /** Count */
            count: number;
            /** Has Next */
            has_next: boolean;
            /** Next Offset */
            next_offset: number | null;
        };
        /** NearbyEvent */
        NearbyEvent: {
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            status: components["schemas"]["EventStatus"];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** NearbyEventsResponse */
        NearbyEventsResponse: {
            /** Data */
            data: components["schemas"]["NearbyEvent"][];
            meta: components["schemas"]["MapPageMeta"];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
        };
        /** PageMeta */
        PageMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Has Next */
            has_next: boolean;
        };
        /** PlaceMatch */
        PlaceMatch: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** District */
            district: string;
            /** Address */
            address: string;
            /** Longitude */
            longitude: number;
            /** Latitude */
            latitude: number;
            source_coordinates: components["schemas"]["SourceCoordinates"];
        };
        /** Reference */
        Reference: {
            /** Label */
            label: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** Review */
        Review: {
            /** Approve */
            approve: boolean;
            /** Note */
            note: string;
            /** Event Id */
            event_id?: string | null;
            new_event?: components["schemas"]["EventFields"] | null;
            /** Artist Ids */
            artist_ids?: string[];
            /** References */
            references?: components["schemas"]["Reference"][];
        };
        /** SourceCoordinates */
        SourceCoordinates: {
            /** Longitude */
            longitude: number;
            /** Latitude */
            latitude: number;
            /**
             * System
             * @enum {string}
             */
            system: "bd09" | "gcj02" | "wgs84";
        };
        /** SourceEvidence */
        SourceEvidence: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            level: components["schemas"]["SourceLevel"];
            /** Is Official */
            is_official: boolean;
            /** Reliability Score */
            reliability_score: number;
            /** Evidence Url */
            evidence_url: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
        };
        /**
         * SourceLevel
         * @enum {string}
         */
        SourceLevel: "authority" | "trusted" | "lead";
        /** StatusHistoryPublic */
        StatusHistoryPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["EventStatus"];
            /** Note */
            note: string;
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
            /** Source Name */
            source_name?: string | null;
        };
        /** Upload */
        Upload: {
            /** Image Base64 */
            image_base64: string;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "regular" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Work */
        Work: {
            /** Name */
            name: string;
            /**
             * Language
             * @default
             */
            language: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Released
             * @default
             */
            released: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    artists_api_v1_artists_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_artist_api_v1_admin_artists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtistInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_artist_api_v1_admin_artists__artist_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtistInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_v1_posters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    upload_api_v1_posters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Upload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_poster_api_v1_posters__poster_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_api_v1_admin_posters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    poster_image_api_v1_admin_posters__poster_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_v1_admin_posters__poster_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Review"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    background_api_v1_events__event_id__background_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_candidates_api_v1_admin_candidates_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["CandidateReviewStatus"];
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCandidate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_candidate_source_api_v1_admin_candidates__candidate_id__comparison_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_candidate_api_v1_admin_candidates__candidate_id__enrich_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateEnrich"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_candidate_api_v1_admin_candidates__candidate_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateApproval"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_candidate_api_v1_admin_candidates__candidate_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateRejection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCandidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_admin_events_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                q?: string;
                published?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_admin_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_api_v1_admin_events__event_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminEventUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_event_revisions_api_v1_admin_events__event_id__revisions_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventRevision"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_corrections_api_v1_admin_corrections_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["CorrectionStatus"];
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCorrection"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_correction_api_v1_admin_corrections__correction_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                correction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCorrection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                city?: string;
                page?: number;
                page_size?: number;
                date_from?: string | null;
                date_to?: string | null;
                category?: components["schemas"]["EventCategory"] | null;
                attribute?: string | null;
                sort?: "newest" | "soonest" | "ending_soon";
                time_scope?: "upcoming" | "past";
                q?: string;
                when?: "any" | "today" | "weekend";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_events_api_v1_events_map_get: {
        parameters: {
            query: {
                west: number;
                south: number;
                east: number;
                north: number;
                city?: string | null;
                offset?: number;
                limit?: number;
                date_from?: string | null;
                date_to?: string | null;
                category?: components["schemas"]["EventCategory"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nearby_updates_api_v1_events_nearby_updates_get: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                radius_km?: number;
                since?: string | null;
                until?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_correction_api_v1_corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_meta_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
