/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Map Events */
        get: operations["map_events_api_v1_events_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Correction */
        post: operations["create_correction_api_v1_corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_v1_meta_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoriesResponse */
        CategoriesResponse: {
            /** Data */
            data: components["schemas"]["CategoryOption"][];
        };
        /** CategoryOption */
        CategoryOption: {
            value: components["schemas"]["EventCategory"];
            /** Label */
            label: string;
        };
        /** CorrectionCreate */
        CorrectionCreate: {
            /** Event Id */
            event_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "time" | "location" | "status" | "source" | "copyright" | "other";
            /** Message */
            message: string;
            /** Evidence Url */
            evidence_url?: string | null;
            /** Contact Email */
            contact_email?: string | null;
        };
        /** CorrectionPublic */
        CorrectionPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["CorrectionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CorrectionResponse */
        CorrectionResponse: {
            data: components["schemas"]["CorrectionPublic"];
        };
        /**
         * CorrectionStatus
         * @enum {string}
         */
        CorrectionStatus: "pending" | "reviewing" | "accepted" | "rejected";
        /**
         * EventCategory
         * @enum {string}
         */
        EventCategory: "performance" | "sports" | "exhibition" | "festival" | "market" | "public_culture" | "pop_up" | "seasonal";
        /** EventDetail */
        EventDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            /** Summary */
            summary: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            location: components["schemas"]["Location"];
            /** Organizer */
            organizer: string;
            status: components["schemas"]["EventStatus"];
            /**
             * Last Verified At
             * Format: date-time
             */
            last_verified_at: string;
            /** Confidence */
            confidence: number;
            /** Attributes */
            attributes: string[];
            /** Is Ad */
            is_ad: boolean;
            /** Is Demo */
            is_demo: boolean;
            /** Is New */
            is_new: boolean;
            /** Is Ending Soon */
            is_ending_soon: boolean;
            /** Description */
            description: string;
            /** Official Url */
            official_url: string;
            /** Sources */
            sources: components["schemas"]["SourceEvidence"][];
            /** Status History */
            status_history: components["schemas"]["StatusHistoryPublic"][];
        };
        /** EventDetailResponse */
        EventDetailResponse: {
            data: components["schemas"]["EventDetail"];
        };
        /** EventPage */
        EventPage: {
            /** Data */
            data: components["schemas"]["EventSummary"][];
            meta: components["schemas"]["PageMeta"];
        };
        /**
         * EventStatus
         * @enum {string}
         */
        EventStatus: "announced" | "on_sale" | "sold_out" | "postponed" | "cancelled" | "ended";
        /** EventSummary */
        EventSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            /** Summary */
            summary: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            location: components["schemas"]["Location"];
            /** Organizer */
            organizer: string;
            status: components["schemas"]["EventStatus"];
            /**
             * Last Verified At
             * Format: date-time
             */
            last_verified_at: string;
            /** Confidence */
            confidence: number;
            /** Attributes */
            attributes: string[];
            /** Is Ad */
            is_ad: boolean;
            /** Is Demo */
            is_demo: boolean;
            /** Is New */
            is_new: boolean;
            /** Is Ending Soon */
            is_ending_soon: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Location */
        Location: {
            /** Venue Name */
            venue_name: string;
            /** Address */
            address: string;
            /** City */
            city: string;
            /** District */
            district: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** MapEvent */
        MapEvent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            category: components["schemas"]["EventCategory"];
            status: components["schemas"]["EventStatus"];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** MapEventsResponse */
        MapEventsResponse: {
            /** Data */
            data: components["schemas"]["MapEvent"][];
            /** Meta */
            meta: {
                [key: string]: number;
            };
        };
        /** PageMeta */
        PageMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Has Next */
            has_next: boolean;
        };
        /** SourceEvidence */
        SourceEvidence: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            level: components["schemas"]["SourceLevel"];
            /** Is Official */
            is_official: boolean;
            /** Reliability Score */
            reliability_score: number;
            /** Evidence Url */
            evidence_url: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
        };
        /**
         * SourceLevel
         * @enum {string}
         */
        SourceLevel: "authority" | "trusted" | "lead";
        /** StatusHistoryPublic */
        StatusHistoryPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["EventStatus"];
            /** Note */
            note: string;
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
            /** Source Name */
            source_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                city?: string;
                page?: number;
                page_size?: number;
                date_from?: string | null;
                date_to?: string | null;
                category?: components["schemas"]["EventCategory"] | null;
                attribute?: string | null;
                sort?: "newest" | "soonest" | "ending_soon";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_events_api_v1_events_map_get: {
        parameters: {
            query: {
                west: number;
                south: number;
                east: number;
                north: number;
                city?: string;
                date_from?: string | null;
                date_to?: string | null;
                category?: components["schemas"]["EventCategory"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_correction_api_v1_corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_meta_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
